apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-core-application
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: dotnetcore
    spec:
      containers:
      - name: dotnetcore-webapp
        image: 049841195927.dkr.ecr.us-east-1.amazonaws.com/frb-repo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-core-application
spec:
  type: LoadBalancer
  selector:
    app: dotnetcore
  ports:
  - name: hello-port
    port: 80
    targetPort: 80
    protocol: TCP
